// 示範用公屋資料（香港公共／公營房屋屋邨）。
// 並非官方即時數據，僅用於展示查詢功能。真實使用時可替換為 API 或官方開放數據。
const HOUSING_DATA = [
  {
    name: "彩虹邨",
    region: "九龍",
    district: "黃大仙區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1200,
    rentTo: 2600,
    units: 7400,
    completed: 1962,
  },
  {
    name: "華富邨",
    region: "香港島",
    district: "南區",
    flatTypes: ["二至三人單位", "四至五人單位", "六人或以上單位"],
    rentFrom: 1500,
    rentTo: 3200,
    units: 9000,
    completed: 1967,
  },
  {
    name: "愛民邨",
    region: "九龍",
    district: "九龍城區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1300,
    rentTo: 2800,
    units: 6300,
    completed: 1974,
  },
  {
    name: "禾輋邨",
    region: "新界",
    district: "沙田區",
    flatTypes: ["二至三人單位", "四至五人單位"],
    rentFrom: 1400,
    rentTo: 2900,
    units: 6600,
    completed: 1977,
  },
  {
    name: "瀝源邨",
    region: "新界",
    district: "沙田區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1250,
    rentTo: 2700,
    units: 4600,
    completed: 1975,
  },
  {
    name: "石硤尾邨",
    region: "九龍",
    district: "深水埗區",
    flatTypes: ["一人單位", "二至三人單位"],
    rentFrom: 1100,
    rentTo: 2400,
    units: 6000,
    completed: 1954,
  },
  {
    name: "美孚新邨",
    region: "九龍",
    district: "深水埗區",
    flatTypes: ["二至三人單位", "四至五人單位", "六人或以上單位"],
    rentFrom: 1800,
    rentTo: 3600,
    units: 13000,
    completed: 1968,
  },
  {
    name: "長青邨",
    region: "新界",
    district: "葵青區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1350,
    rentTo: 2750,
    units: 5200,
    completed: 1977,
  },
  {
    name: "屯門友愛邨",
    region: "新界",
    district: "屯門區",
    flatTypes: ["二至三人單位", "四至五人單位", "六人或以上單位"],
    rentFrom: 1450,
    rentTo: 3000,
    units: 7000,
    completed: 1980,
  },
  {
    name: "天水圍天耀邨",
    region: "新界",
    district: "元朗區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1500,
    rentTo: 3100,
    units: 8000,
    completed: 1992,
  },
  {
    name: "東頭邨",
    region: "九龍",
    district: "黃大仙區",
    flatTypes: ["一人單位", "二至三人單位", "四至五人單位"],
    rentFrom: 1200,
    rentTo: 2650,
    units: 7600,
    completed: 1982,
  },
  {
    name: "北角邨",
    region: "香港島",
    district: "東區",
    flatTypes: ["一人單位", "二至三人單位"],
    rentFrom: 1600,
    rentTo: 2900,
    units: 2000,
    completed: 1957,
  },
];
