// Illustrative dataset of Arlington, VA apartment communities located near
// Washington Metro stations, focused on an easy commute into Washington, DC.
//
// NOTE: This is sample/demo data for showcasing the site. Walk times, rents,
// and ride times are approximate and NOT live listings. Replace with a real
// data source (e.g. an apartments API) for production use.
//
// Fields:
//   name         - apartment community name
//   station      - nearest Metro station
//   lines        - Metro lines serving that station
//   corridor     - general Arlington corridor
//   neighborhood - Arlington neighborhood
//   walkMin      - approx. walking minutes to the station
//   rideMinToDC  - approx. ride to downtown DC (Metro Center / L'Enfant Plaza)
//   rentFrom     - approx. starting monthly rent (USD)
//   rentTo       - approx. upper monthly rent (USD)
//   beds         - available unit types
const APARTMENTS = [
  // ---- Rosslyn–Ballston corridor (Orange / Silver) ----
  {
    name: "Central Place Residences",
    station: "Rosslyn",
    lines: ["Orange", "Silver", "Blue"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Rosslyn",
    walkMin: 2,
    rideMinToDC: 7,
    rentFrom: 2400,
    rentTo: 4600,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "The Wesley",
    station: "Rosslyn",
    lines: ["Orange", "Silver", "Blue"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Rosslyn",
    walkMin: 5,
    rideMinToDC: 7,
    rentFrom: 2200,
    rentTo: 4100,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "The Eclipse on Center Park",
    station: "Court House",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Courthouse",
    walkMin: 6,
    rideMinToDC: 9,
    rentFrom: 2100,
    rentTo: 3800,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "Courthouse Plaza Apartments",
    station: "Court House",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Courthouse",
    walkMin: 3,
    rideMinToDC: 9,
    rentFrom: 1950,
    rentTo: 3500,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "Trove",
    station: "Clarendon",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Clarendon",
    walkMin: 4,
    rideMinToDC: 11,
    rentFrom: 2150,
    rentTo: 3900,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "Lyon Place at Clarendon Center",
    station: "Clarendon",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Clarendon",
    walkMin: 2,
    rideMinToDC: 11,
    rentFrom: 2300,
    rentTo: 4200,
    beds: ["1BR", "2BR"],
  },
  {
    name: "The Berkeley",
    station: "Virginia Square-GMU",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Virginia Square",
    walkMin: 4,
    rideMinToDC: 13,
    rentFrom: 1900,
    rentTo: 3300,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "The Continental",
    station: "Ballston-MU",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Ballston",
    walkMin: 3,
    rideMinToDC: 15,
    rentFrom: 2000,
    rentTo: 3700,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "Vue at Ballston",
    station: "Ballston-MU",
    lines: ["Orange", "Silver"],
    corridor: "Rosslyn–Ballston",
    neighborhood: "Ballston",
    walkMin: 6,
    rideMinToDC: 15,
    rentFrom: 1850,
    rentTo: 3400,
    beds: ["Studio", "1BR", "2BR"],
  },

  // ---- Pentagon City / Crystal City corridor (Blue / Yellow) ----
  {
    name: "Gramercy at Metropolitan Park",
    station: "Pentagon City",
    lines: ["Blue", "Yellow"],
    corridor: "Pentagon City–Crystal City",
    neighborhood: "Pentagon City",
    walkMin: 5,
    rideMinToDC: 8,
    rentFrom: 2250,
    rentTo: 4300,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "The Bartlett",
    station: "Pentagon City",
    lines: ["Blue", "Yellow"],
    corridor: "Pentagon City–Crystal City",
    neighborhood: "Pentagon City",
    walkMin: 4,
    rideMinToDC: 8,
    rentFrom: 2400,
    rentTo: 4800,
    beds: ["Studio", "1BR", "2BR", "3BR"],
  },
  {
    name: "Crystal Towers",
    station: "Crystal City",
    lines: ["Blue", "Yellow"],
    corridor: "Pentagon City–Crystal City",
    neighborhood: "Crystal City",
    walkMin: 6,
    rideMinToDC: 10,
    rentFrom: 1800,
    rentTo: 3200,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "Bell Crystal City",
    station: "Crystal City",
    lines: ["Blue", "Yellow"],
    corridor: "Pentagon City–Crystal City",
    neighborhood: "Crystal City",
    walkMin: 4,
    rideMinToDC: 10,
    rentFrom: 1900,
    rentTo: 3500,
    beds: ["Studio", "1BR", "2BR"],
  },
  {
    name: "220 20th Street",
    station: "Crystal City",
    lines: ["Blue", "Yellow"],
    corridor: "Pentagon City–Crystal City",
    neighborhood: "Crystal City",
    walkMin: 7,
    rideMinToDC: 10,
    rentFrom: 1750,
    rentTo: 3100,
    beds: ["Studio", "1BR"],
  },
];
